language: node_js

notifications:
  email: false

sudo: false

node_js:
- '6'

script:
- gulp build

after_success:
- gulp deploy --host $DEPLOY_HOST --user $DEPLOY_USER --password $DEPLOY_PASSWORD --path $DEPLOY_PATH

# Cache setup
cache:
  directories:
  - node_modules

# Variables
env:
  global:
  - secure: P6zCv0oxFG+0ULSBeZUD5gOHidTS1HJjeL7z1xgvoEaElCDWHwL3Z/InXPRYz30oWc6yO01CMU34a+0L6iNRVquqh+eXqaGeJeKDYL4PIgVBwCCfuC6MuvfGZxXQjD3AIdJYaihl5zHi3zBV/YoLv3yArvncMzAJ6WJxE66OJ2OrMPjrRDouyuEQhFuj5lJB1Tr5mQOaDG/e3DrB+9z0YkeynAGB0hE+28hNSimSQNmFirZpoe2vI/joxvbAAZVmELbG/ioYHLcCll1u+AnXLzmzuAYGOhrp5MDrr2M3pv8dG6g1ViL/SQWl7WaV88hKesmLq15IvFqISdTyGhohMeDD8yWnnYQiGzQkE90i51FluZ9B9pBHBL32LDmLw7sKYTslSAxrhF43pkD0QGiO2QY50wIwrdaiDFfZ7ZQhlcXRPAO78xXwJqjCXrygJJQXbK+sMo0mzIuE8QIxoo3DxDQeGB6Hygs0YkMLWknH0CtqNiygd4hRq8AfeRy0bvokzDyQUdA/A3qMkSdMnPOmLO4yfVVAk1iHjBcIQcYtcOm/EXtopJb2cDFumxsCUyObPLna5BlMekWRtEpM1OJIn9Q1vhlQZTK/Uj8nLHYTxSNjS0QG9NtRvSp26PBOd6t1Cpb+x/xEuaqOBjUH8OcDEhjaFLuYH0q9QposqmASgWA=
  - secure: IZuoMmUrFQGnWGs5qfH46+0uAuSubdjHIfA0Bn3cZgQxUTUBM3rBbDnyjFxUYj9w242mqdrseGUyEY6EkncdbG8clo1A6j9hhsbVfwIEYHBg9M2MNMWP0qX/bw1R0+9o8vmfAku2fc5GzZXkyefYKtdsbr7hID/bHTu4w5JLhSRaf8c+t3vl9jZEHDzTFhRYd7ErTUrc7X7IcTq1f+k5hFQMsPI/JNjLzPAHrKeac93hLIQETKqalcI5hS+XZdwsUBcicfyfZqTASwB9HhckB7F2qG3O0+gEO1BDcT5/Pe0wvT9swvqcGJ+ede/9+hKGKwOP4IISS88h0llPahtWYFdLphF4HDrTQcGvUh4544KKrf0tUuWq0xlvy8IKxbu6Yx2cJm5E+c25qr6zn8FAWOcc8omXEU9cKpe8d2nyu2uyZISxTEMJlY0nnYzdx7PbQ0k/UL1/eWG9MYk/8bksIeSxqRe+C9IxCEYFUS4uKMFZJUzXDwPrWovMSEyrDhGMLCbkCSsZ57fqheVK1qBht+oXb6J49TVaKlyff3tjLYOn3zTHBUsiE3JvfBy1P9vIagESyNGB6ZTZ1JWAYlFxRNwxaGr1UgHGA7jaR7nTLTc5qHU7jRAy7QXQjMq/FvB1kXNqfdSpoPeFRphkre7uKSme55ek2aQr62Jvkvs3RHQ=
  - secure: FEMzVAz8Ds0eCPB9qqqUapfSa3DfhYakFo5RtIy/c/le0mJMrkPDY7Zk+rK1vXv+JUDE5Zr7Qr7cltKsfxJz2lZjPG4FbZRdUs3NmiPyXWAmMIfeT1D+iwBHa4MXPXE6DElVkd64cnkHIhEYNZ/rpPho3LBZ/yMdfchO9uQyzeKEsSfd/p+t1trYRtB5DSeNSCrH4jKcM3HPD/MUtzpq1A0EIOyyCG8NuDQP4veLKWLw0Gj6j2nF9dXtjbwWv+8CnMitGzkRe/QNkzJjEVBzTERziHC9G8ubmD1lilrognOC9ryvF3hNQR59FBEPF2vEFTb70ZC/D0EtZPY367VQySZwwlL5dO8sAnZBjyuTQgTSnzh1FMpBIjTxBshqIzf+aIokpdKtc00pEaFneSi02WNSPIMjSR9/wHwWm8lg4shzm2SMZ9atqTCDKG77rIk4o8rmzvNxqtCuqMP3gyyNku8+Bx43A1G2HW9kwKSvNyXKeYy95JzE/JmItmDUKn4LTmCK3aPI5aY2wb3pg0DIWhTtfxiLcvsJo3GGIxhPT8t48tFKCCrbqvfG+shS55c2wJl2/VxcwMDuh49NbiWKr51YTg2wM8quAkXY4tt3wjM0AZsfWild9+Mz0BLSkgWJqsypdkieNOcfuJbuknyZCtIZe9Xs8O+pVhDumzrvXOg=
  - secure: ltU3FjigKKRHfdVicqSkpKh4XQqCrLjHYMS+HXlw7fwa45ollEk24msN/zznQne2YyDXatvZ0IVM4NA37PX/u8MrKMesgnKoJMnjyIpRZQrUlBEvOnO8HJuGkVSTG84F4Uhmy87tRJLPkPsekTMWKaZ8HD/6brh6MDkjnZJ0QW7vmvHLS6dJUysTN4vqiLX9ZIHGgBOV7C2cThWxyz5iMPF8yEIMeYLgQRHMNMMfN3ZmqCDp3XtArWfeOLAihmrDJ9+zdYD1iEdyqQcIyju3H0ybktqfszfb9mYLk5Pnim5sjfnXJnU9Ppyx9qiiQXeLOI02fRPdKlJ+WqhQG3AeqRh0vcYgJ1ZS1PLos0A/NI2MMDrdf7aWc//TtmUYqVfrc9CLeJLPv3kKBkZAWL6uDBhpVf4jmyVZhbc0JBAwKgFzieVYB5zZ6Ld89zBgj0nVcgnXxrlDTfik/2kC751dc1pP56iPOGDu+qNpI1h3wSxvOuqqkashwngjr1ZEvMzbPsTQy9h9wROX0lcmW2hCtK3KTCSmc7F3nXx1cA5af8NkYG2JXW1og0ICbv7KxZUztZGXb47UXAY3UX2aREjli69cyHdzre/dOqmPcBO6+hRC+amhPI9MB8eEYZSwjYNivLCsIoHyoDa60Sa4nh1oEYxba/I7TDenVkV/8xwNEBU=
