language: node_js

notifications:
  email: false

sudo: false

node_js:
- '6'

before_script:
- npm install

script:
- gulp build

after_success:
- gulp deploy --host $DEPLOY_HOST --user $DEPLOY_USER --password $DEPLOY_PASSWORD --path $DEPLOY_PATH

# Cache setup
cache:
  directories:
  - node_modules

# Variables
env:
  global:
  - secure: nUf1cW3n8PYpYkA26sBu6W2WFuWvuceM9DSYPfJbyhAy1E7JS7E3FYq0Z2/xyKC/x0jGgXiclMsVPkBUhkKrWzBhfUc++fZBpvsQKMF/u1DVz4iXRG8U00qTxf+33z1Deblkl9+t9zMw2du67wdw7rivCHOnI/4EyAM6dWs1oMlJujRxWZ4lx3tkeS3bZWveGJ0hKo6qysIO9gAi7kzfdYyY3AA4+6KfCW3v3PrzelrGeX4p2BBLD+27cEyRDCYiIYFMGRtno7lueioBE0Bl3Vzs/adlp2JU0O8wIhGAYPe5OvrCjocUjGgBC+xZEQHnW8n3/1wV/+I2Wk6zcI3l27+TGQ8H4VaJKWJw+u7XBulG1aisD4od72d4ac0ulqmaOeAdG2Inz9vjL+MlsC1r5fDdExpaILWToBoZZEqEmpzmqVjfOBr/BUG4sGKUSzEV6n43OIoxIJ4CVdpJplFiCDfO4dHDOcaFy+fKvzJkJJYVDhvyQonXWNYEe/r6Gm+pAjVkH943g2y3u8uwF9lfF7w9699rqCSPQpZg+cDPJNxwxYCCsmnoFiG7yzdMHAC3iOefgZ3Hg//rHaG27X5zJRBmI5BxB3LQK09+0mytNofxFLpSPyyI5eVejzhAJChGc+QIUaBK3dZRiro/HNLB+5NwOJlkeT6uFWoOAaSuDd0=
  - secure: sw5/nDgAKFGOsjufv+ExpYoP+Nn13H1ebIDVMGjQzUG+HipR9iHzsbULTYZCGrtUoaSbtIbbYq+7tnkf6s1PJUGIuHDNhFQ/yvgrwu9VLbS9TeQJjFnSk1f8XhaTZjdxAJLKRYhGOu7ALaOOeVuLI6YkCzch0Qu+/UdHkRe4RDxwZXE2WLNDgnAK5VJq/IER/rj/UyIrFB0xO59uvJBgwigPvRN4ourV39waK9g7WdI1H5XYikK3a3oMhcDE9Zmrdj5KCtWObja++mCLXIv2U4Lb1DV3wAN0keEnbaF7tO3wZTdTWmQKSBSazkzAj9hJsjfNeMjvcn3bIcuAorbPyKVIh4oh/9XsXuvSADX8l8mtVFaYPhIjuF4PPwfmcaZUYY86IXZHPRC765KPNysD24jXdwusjZHObM90vOxKG35YafFCjXzLZaiDfog4R0LtWDuR3uDmuvC2CVg1YC2dJkfSahQYJ8qK9uToJ0txBpQ7esc/xIWOXM6Gda8HiTzrgAucFgfEGkwA5z0L3lCfn+EewkvoClm6PshlldH23fBfpmcnGGkT8b/TPWlauQXlaW9LA+iLEkGrI6kUBCjDVoiQF6Vbo0NRr6wh8sXUTooBuMXCyNOKKsz73napGTwqN6GvXzLtfP1uEuYEwB6T3rpcWY61q8Bh7NxVT855qt0=
  - secure: hDlojh4gdRl5xwnk/AB907H4bkEDpcY6KGeyyzFXTOx87wBDmb8OFTUS3n5irynfgNJLGTxokN0umSRMJIzvqGZ9AbsCF2zfaUIhoY+EVbzI/4LMQZNTZ4Vd7o5PdZ2wMbXxHezEDbdhIgthH1c6zwfWP1rTUnOKB8kOI8hePOPr4pYPL9Omnxx/LKs7HZemKvBm1aYrUBZNMb+bL5PpuL+MjakNX+VqkwMK1kqMHSgbpohUH3kE+tNHAMFyOGGzsowhd20XumZvxSyTB+pf8IEPrXPFQyai1QvjqoADGVfpwXoaTekNhpo0/PXsAqwxuquSbYuvFSNp2k/XEHYt6cU1Pbujt3+o3EoHVWkJtVKU1S5X9bzD5qAeU3WF+kRdBRHez7X3TwpS6wtCKbcFSjAt3ncQiPjAtot7NpfdWFxFAfjB8Wq7clagcGGwh6+ANeO7EJN3kizvVE1uwj/K3mugJbdN8MbalaMEdzapsYZqSpuwR3KOa14wBhY9lVybzUHGABOAE1T0nfUrhJD3B0e3V0VIzySPnzygAxYYDJ0sFgHTMWuA9eetzbASgA12Ea5UW5OwRfgBbnm+SR7cQLdEAumFFKUR8YYhz2ABAxPBFdzDiBsbI/tQRgDzDSgq6VEcjMO+avoxBnor3SWBL7g8w+D+qhGuI8wd+gnv3Pc=
  - secure: h89qZ73SrtfD8YyhC8gFJTwc9Tdrcnys8FBcIP29zVLbwBngOfdHAu+B9XEHsz69Cqx3Rc96jJGbjWh5CV5F4TUHVyzINe6GXmVP3Yrhg9f90Ye1N+ZPc3CkvH8BwxROYo3xccQUrYrFHHQA5zgKVF3wSDUWjd/Rp2fymEuz5NYUPpLjQSFQV4KspKfudy7yiuqK6hOUwCZaq7ndQvvXhEBRF1AoLoMFkOMbXx3cVPehAA9oKOfT+MUyrM7d2irmoAev+l05vJXlA1M0DcVnYeZa5c8qQfcz7wrAohR9MZSvg0IqYiECCABKRk/FGnyNOWRPzPkTSFEjoHbqHdBJGCdOtcIQ+GigwgQARD8zS3XCWGOAg9hY2gnP5drRMLH656vhTp5Yf8Wzm/mCCF+jmYgYF4wd8ViQ3o6+HFp1SHcwRKaVZvIEFIY2vL51A58uZKes/0Jl2+MNCxSig1GChjlU6L/Uvrb7f7KdqNt5MYVSPcIq1CXuLWzHpUyu/lc4F0IwXFGo3XmPoeOn3cZRaZqDDmC+XGqbTQiHyPdWqw4NhTxGyhbKt/f8GcmecTe+aA+i0Dh07Eu8YxM2EewjJiLGpvqJ6yMMtCt0fW+s0MY5DqtFXN3RAxxmBjaZ6WY4YRWobKIqlYnOWuITm5T2/uuUeswyZuzESA8YoKme/CI=
