language: node_js

notifications:
  email: false

sudo: false

node_js:
- '6'

script:
- gulp build

after_success:
- gulp deploy --host $DEPLOY_HOST --user $DEPLOY_USER --password $DEPLOY_PASSWORD --path $DEPLOY_PATH

# Cache setup
cache:
  directories:
  - node_modules

# Variables
env:
  global:
  - secure: rYczBAP8YrevXqzg0m5FJGQ+hKg759J2vD5zg7GzzHMh5Dmd1QNMiBg3TewpClJKJcbnQY6WPfFN9pMCVMNs4zmcev0CBh+EBwaEksMBn3JtkVfF+B8DcKwfYM43Cn0LbCQ9K4ZYqRjB0kJq0o/p31T/2EjSlHnpw/qfl2+/u5KfIDapwn6l7zaBUcQPAeJUg2D6TTVwckZnczf1BAy0EcNZQo7ZWbltjDv7il3PD7NvEty7OJxqEKitjaKG4WoDDsSjNCMCGIkJUskdeosbiIe6dLaJZuS1Igq9NpfhIbcru8BHtgWz3cPxn7quUyUFuFNBwky5X4QG7qRUAviMez0k4Pw+RWCbE3ntFyIfRrjB4KV2MUVSlvR4TMwS0ED6OAR1FeLY8klYF3QXXThA1xKtGA/3fGahJzbbmhNSYS4ouOGo9XPdlq4goYmQfKSqaozZLSsTGzNEtaFUARgqvYC9M4wb+ZjRZVq3hX+x/qVlzMI6+3Jx4GA0Xndcm2pPMH1MLazLDPqIsuWTSQiYxL6pijXjbA+eB6oMvfcj5Wb+0JKpsJ5/ixzc55ltb0RhlQM+K/eqFzV6juffD6boyG6N5EBPM1Ag47sTspZyxke//pWoS9ZIVb7433Ef8ZG2VTYsol6KX+1I/JX6N5Dg1vJttBveWM4jcVXOezmghXk=
  - secure: CexHPkvwJVYVAsUGIkk6eLoJfTupHH4cCHjIfsayaNQC4Pb8pMQZB8ueWBbsDCe04Tvw52kB7KWn5NMn1NHiuq5Xl0si34rVeKG9Tm3vJ36oHZVcaLlrWPs7LumYk/u2xSkCxcYOTjYTB+fOasdpHFDY8lP3crJf2jhzU8zd4L+NQOqK2ddQtbYI0cdy4HX85ICuJibgC+yEH6GXiTWjNaknVcjCLrGUqU0aG8xIU2+92/769YHUyqaqOVEjGhwTA+4CBh8rqSeAuWtUc27bjxXxamISLCCubASvY3Zu5ZW3rEas0GNUS+Q/RG6+RiPAQEO8cB/8/sE9QdQPXqtrwZua7pyFkcnLyO1WMkPv5dScTz+kydlJmPVHe3HGaN4aeWziqZqX/D30LfkQnuVqD3tXjHYp1f081dRKsqDLM2V6eIW4gMAgVqyn9HF2OOeP11nlyImaa6PN0xPWqkBGIUBWFnUCIhOhJYzNVCU/kkR7Nxo331/6gckWR1eBkjnZFukbBMTqKEgUgqz4/iXwFGFMdErzcXghwGmjdBUz6tVM4yNTCOtydJxbH1sQYnjwcaAOkIoueA38qldxdal7JHGEQWk5OgnwLthH7u6c94B41kFC5BsC30DYZzJXAkC88B4a6XbuP33A4ECGqhWIQDABKNF9ypDWLIcaP/02ZFQ=
  - secure: A8y3DYCuaqVFT25/jnfn5B1+wTcg82ndReJqiI1a7lV/DJBi+56bxfct8Fk+PhOuffOvOdzxxo/wCDFrtzfEj4CQ0D+Ja8XKPmcqyem5qStBv2NojJRxTZvqDq14vXDNtr7GwTR5QcmpnGX0zbupa3tpR79QzKyqY8SE12GnpE5iVUwn1PQ1xJxT+XriFxq81xwNG91hTF1QiNJmcyP1Dl6aeg06EG6UdTbOUHZwfEqsVb872hcCGD+kljOiSi8LEVVear12gF9183gnTK/kTq6MJNG1/ZmLp+27TwqkbLhr6gixDbL01C8TLN4ti7JgYE5R9I8lH+xNnXSJozaiTTEIvKSeIbvujSbHFHRN/fpgZ+rhV8jJXT3Ij1AQJc4unWxru0kOuGBBjEZhe3CgFb3FLLJEsgeE47OUbl0q33FQrVlPGbHlNU2HIvIY8jij8US1LpCkDSj3/gLFOlidFJASwXV7819yVq9zSn4hcXBa5CweY8PshVoXZqhvybDwtWW1S37N1iW0WAm2+UpgIzyMoFFpfmPW49pD1HViBgivJnYpKaMcWAA5u1QZ9/UDZZxc4Qs+t54yVh5J7w1Q48yG9ze2ClMWKhg7DaBMcgzrPjqKLu9ZwwvnCLhN8QqzURymyy6uafUO0T+jfr6bpKkIVAPzjFoGqp+iLBRxEBE=
  - secure: fvsQ/Z3HZYG7w8JRR5TER+J/kH1MrdYJXu9k+dsgIcoBaM7ZjmBL1etAHk7EGgG8wUx4xjBqgiZG9c2CV3SxNqfAL+R218iNJ4jrLqi5CUAeqJipBAh34SbjvJRYaZ3JlaVyEBND55WUusrSBA/bk6Dh/Peo8HM6gG61yz6HVDld8PwVukuqsjOapqkUoQ52/sod4vY8dUUZmgh+ij6CaU/KZaLkLIzhZWNkwKtb0i1C9PwweDVarIHz1g77GNq+u4hnZk5fj6Ap/w+qHR42rc3H/3qS2ZDyqGKX2ze7QEeE44xwLgpkYKWOZ4zrl5g1pHkfjF33SElHOr9L4iq4FLRdO3lDjNo099ZJTzZPEcSMWrwXiFVmrHVzmmOZsHkhG8e0haDHjbfG/yg10zIXsW7pxt7BER0gLmRdKtx0RNSPEzoLvrWugU8JW8WZipuRS39Lt9e65NF33gCvXXtJjqbWobSCmHtVcz1Y0Zp1Rd3ve4f6sTzqxy96NchAI7jn6ouJjo3KzdysNGc2R7PRFfHdmTo+0ZGAW2eOjTBTo+0nZ+yyECSlsmBfxtId9b+BM7HWto+NE0vlnViwX4jA88tTkGWaYqxe4gxLSU/j58MExApPzwRKyU2NTQfs49HUPC3gs2hxNo+nhZH7jTk79AFlbRsEP9CVuS+kboBs3u0=
