language: node_js

notifications:
  email: false

sudo: false

node_js:
- lts/*

before_script:
- npm install

script:
- gulp build

deploy:
  provider: script
  script: "./.travis/deploy.sh"
  skip_cleanup: true
  on:
    branch: production

# Cache setup
cache:
  directories:
  - node_modules

# Decrypt private key
before_install:
- openssl aes-256-cbc -K $encrypted_7baf1f332e19_key -iv $encrypted_7baf1f332e19_iv
  -in ./.travis/id_rsa.enc -out ./.travis/id_rsa -d
