language: node_js

notifications:
  email: false

sudo: false

node_js:
- 'lts/*'

before_script:
- npm install

script:
- gulp build

deploy:
  provider: script
  script: gulp deploy --host $DEPLOY_HOST --user $DEPLOY_USER --password $DEPLOY_PASSWORD --path $DEPLOY_PATH
  skip_cleanup: true
  on:
    branch: production

# Cache setup
cache:
  directories:
  - node_modules

# Variables
env:
  global:
  - secure: pFtkEEu5xZv/ZicyfWq0oqBSqhtn90J/+aObcVgsWcksJ1fOo+UgQ/BRxiL81ze2LNImQtdPPFMc0YQ+n9q+Ujaw7IDdyZ26JbmVKoJYNDlSxy3sW2e/eBueL7D56ceJgCJZrbmwoOkaSpv1Xfo+p9rjx23XoHIGaCipjh4zrPW1DC/LbiBMofIefoMKbAn3GGf8VpXSb6DL9goRUdVVHWCDYI/wzS44Tsi4LF+A6Fl6Tt6GCxRP+YT84akW5AjjI64/0s0rOb1k8TP3t9M0JrAVE3n6LtqKYDYql0EVnMyS6IBnT0IM7zBgiJGxYCDtvoxusvTDPGMiXNDjhIvw+F5uVFvTwsCqHHKJKX9jetbpW767b0dDm50ywj8cQq0RaWRlUNkwpjvqttvJrzkJc4vMFtPQc5aKGRu7ybSsPl981sTWflxUlq8YjrV0ITQA8Xh1aF3XI29HyqGW9Cz6EobLfNqnGTAG9gxpcDPi4uMFFLqX6GHbYMuD23JEmXffybcVF9pwSAbn3c5KkR5N68nfoftXitDYG+skLAmjBw+hnobnC+0vSqGwwDkWa3zaic0i9uCO6CRGmej9Muo+Nfl7xUf9ujYqYSzDi+dFL6bi9KwRg/A4gEElEJ0pfgtd83c/fG1qU1NXnGm63QsypjoayBvIaIzP8FBYMGd48so=
  - secure: uGQscfUQU3wfNOsuO0GxHYE2S3E+BNcr5+6nO/UwEoe2bY25Fuxg+VGh2wS8cDjCT8RkydTKoxpJF4G3G7f4cvHrYZ0tPVHtLNv1i1PL80PBJVBXJWwVDh2Kt3Wjp3v93gr076dCKzc58HqBKoBzjoO5xFVw6XPWCBOtUZxkL1XIwIbFaRvGvuRKVA0KIgp7MusCbYuwCXymP718Zq5CDq0r8B4uENWXVFpwzQwSKF73KPsMjztKMjXhLwYWH9FrlP4FMFi3pMb4m/u28xJr0AEne27rmO+qJKHx/Zrq8ARqlaxIBOh3vqszbqKdPKcNwKwjvdN1a9JXucLrf83RkHdbPCCeKEroXLhC4A4oAUdLNiM5vLjcTnjfJ0e5Z/Cz0XEeZBCiEq1g0nHzEbhN2r+nuLm22RzDcfNoGjhPQK6yR95n2wizYnQwBRHc3DKuswqhfN9EZw6eqtFVWG2qiO/rbtf/rDr1h3XqbZAPOx2VwVJmWvSbYEhcS+7A9LAnYEK1jTF78hXbi/m8BaiQxOk5w5/YwmW4kJ38TYGLFFq9Rxr5nA3tKMsLJUPhRPQs7UU9OwkLnWG0X040zk/u0hBuEurYqUNimiS0AywptfFO80zS6Fe2cE1IU57z+oITWxD0fHGnaZaSIxZ3kLwBmg95DsuSmVXRQSg5pG0ealQ=
  - secure: GEt1CsstFRgX0C0BducpBHjVeNhaFF4jhjX7OWSAKvAIiPItylK256J5QgViZDiRKHvxc9E6Y4DQ0QgICTY9jJQDJq+lxfpKf0lltJyHey+WC+T1rJx/VBJW5MEGQ+mNhZ8zvpg8yTkfjR69tzkCtOH2WIch21B4B8U0EjAm8JeAdi0+0O6emDiHHq2cl8I+g+vXB+pWBBlacGcC3LK6Vsy4PTV29MPaAFnchMkCC/PYhH/nS+8PX6Uu/9FtE8DdsmD2HtgCwAuHsGY9xUElRtMeTA5XfLbgwZBOUyzMzIAJUbPLUETKPNXQ+rJSZbTT9tlLRPS9IKJelIPfYR/QjeheN4tnVkpzm7IqSrOM1uV8cSCvaEekQSjn+5qZ2gr9ghwrLGRfK+pB0hhY0MfHlKlw0cV15CCOmlzRRL3BIJIaJUKoaov9MTqJAPmEc52232NRh90LyjJveKnzSuNyBLOoeQIbkOceJsKLgVKVSp6XJxm15D2C8wIP5LgXLgJUE85cWt04S6InggoXKzRt/35gc/u/AJccq4iLIdCe+5jDWwnBzUlunt2BdNequQW0sT9tyMWfbbbXC+Mxd2U7mGd/fhYc2Pog2qc2tl8Zsqs4wW/gfnelCvb+BkDdQ++LbpFkubhkUtL/YKC+j1sLR30E8ssrskd0QJh9cNOB0Xg=
  - secure: Rzq7THk2q2L8okYettcjiR5lxbD3CSqSLcuLjLClXQI0EiNmCTLxjm2tiUHJpz4lr1YClu/XXjSLFZu1Ocyp3/WeI1Wc6GEJfkqXPNmjrklwClDg1mUdCVCiZ9GCZgFIlnjRX5ZEIMy2XCeLxwstogTK5XnUN8evXqW+czbziltuhPpG0i8pKDUbTSedCQJQKcxmR8OjDizX5sj+cKFRFGaFdRF7YFC6bC9I3YRzwyrAleSUIRuLclAE1Mlh2W6e4PetK85ZHCIUwbnerjcbYs5fWQhkezy5WGdld20RlZeQz00VZfIiRGor9fF9MPfKTNFyKssnIcDP+FoD4VHiXl8pww2JAd9CxeBk4OWUZ0mQa0MLQt4bBSkkP1VcVj/9NSRBgMbDnMPgvaUDPDPbfP9DdGKy9O9A0jxrDZMW3Flg+IY2NkMERuMONqk7Qrg+f1ddoUhkorxxY5q7vl5pqUHDM01ya8lFm0C/Lv1V+qChZXaOhvxtAj0gOWDds8hwsl4sFr4vX7To0ziAzESLVUv12XZDJhnLTxFMoU2NX4ojUUmxk/pyHqTGDQA7xr7pz7IOftxJUnOwrspAhWB/xiZgx5Z+sebHrEMcjc9EXpA7KyaAldqRTj6bCO1sq11itGsvmHc/OMl21XWsH9fnSRghXX1Vgp71cLy08pFQb8o=