language: node_js

notifications:
  email: false

sudo: false

node_js:
- '6'

script:
- gulp build

after_success:
- gulp deploy --host $DEPLOY_HOST --user $DEPLOY_USER --password $DEPLOY_PASSWORD --path $DEPLOY_PATH

# Cache setup
cache:
  directories:
  - node_modules

# Variables
env:
  global:
  - secure: jTsHftN7vmWG+29H7+NNjojRQUfcX63D5DN0MabBC98uMdBrvW+iOWJAo30cIS8RL2itC8jEaXu8MxFTnusIo9cyqlEK1uTr3dFEaskaAH2b7AzF6thBVVr0CrHAkBZjUicaIBU0y8kgzln8lrtdWOnOqqrxoNJi7zLqAiV6x4eVH3Fc4o/PON3Si97KSAxCgzzHsU5dOEiMjYmP/AkMnPsvJdqBs5psOCYyJ2YKziMYLOY8bFmjQwbbTlcpvWNVB44b8ki8NpaMilDawAsVve72vCraK1b6G/G1jARDIZwJJ6/P9mM/W/QAL7nY7xbnN9mJJJ7hmrLOMoc8dPpJMbZmn1rWul+Bsgk/4F4wRz5Tarzn/a2MAdObcAENzkJP/JNFeKDfhWX5l7YCKjIcA5YO8Q7A5ncuunStYgwPUAfek3gDBghI7N3mppw0PJR01iwLm6TlUQBkY2ThFhfu8LdlIRPfP8UtPGyq0j7L5485rDtGaVLEgTfF9VYEZUKjHcakeTQLb8PPVnqDiU6+qHEvz0Y001N4LdH6Ix0cQ6qC/KgiGAt2dQ5TfgapYBDdvryqV1O6J6cXQo2ZjzPL2zvHoMRTPYyoWYSBqZNXK+qdXYUbJtvpVaHu1MSO0SsJLB4bbOSbF+LccYcbsMD52SYYm/QBNDh+N6Qxqbb6mIk=
  - secure: TtFJlFg8igKOBzZFhjWJ2COsKvaFqN5vABDucRB4r7i3Qk1QWPW02m6QqalkXjP0duT3MArZ1g9IA0dONcmOlmiGoahrD11oM3bvwrsuZTXwNRLIfQMg8fb9Dv+w/s9Ha72zei6T2in4oMS4WNxXjuzO0aCluz1GIDyNfqrDT3Hzt/bjjdALQ5Hlg8A27POPtDbeRJCnMzn+MTSMWqGws4U/ie9PRdyrGLO+WcaVKOwslNLZDuQPfSjG7mcc3bhSjjJiDAEq2VEmij3gi4rf4b/h3Ec/8biwZ8275AY4kVBM6dq29EL722NeKGyp5ZbyT1u80nePv3N/FuWbowODzwfY3Z/RnsOHpCRuLuzxejrPUSUPqW5Eagbm0H2LC4bxGyWPGecljJdrFRm9QOJbiRVud9ogk8/z8ZFeNF/rvENA7yW2T7X/RyRjXKiUldabHdIzBp0hFrsiFMKLd1Yrl/ovOH2A4r49zEkAZFZeWEJk+0pezy3f0cE51GYLkTV2rSfw0hxgVOGrOP1ShVjBgxjg/lSJQ72JmqT0XHV6C9AhkX1WHE8bo43Fl89r2bUlLE4KHgyMes76X1rHE4LQTurbmVI/ziHevhraJR7eCa7shBiGc5lCyU8Z5ceYkjrhh4UvD2C1IO0YqLNN3LKOZyQAHWQEOS2gcJVh3QQdWTM=
  - secure: UzcIrUUDVKMx1tDbgm1Kpiqu2jNqK1BGXkMryaFE4VbM5yuwzT4YaBXRh5cW5MlL1nN7/A0uFVtQTMzI7tbM9jg921Nuqugba8SVAb2K2usHbILbU2rA7lrZrVH26YgNfzvZMhbb7R8qt4gXFs7kd1OVNof1lsSxzVlab4sTNTqCHY5RPOW24EAVa+FOmcxlor5gwke55rtf72R7+9QCfCevRePNkEprNb6Vz9kqKDri9vf9Mw6C5e+Gudm8nEq9JjMaya4tFTivATfk4iOAhFluMf3DeYxyha6ywSEQ/OVwO9+rD70JExzI7VJjbslh0yp0q8Va9foo9eIat00YsXXdBbCDpA0BoaPJfBzEk/fzekTekKpNR/5MpR3fry+lcn9UUXFRoDcaM+GTg+E/tcAqKE4juht/UVfJkrPB0lISS7w6K6z4PJl2hki0k/IOFd/vZ6YK9REa1jF2NQ8B510ULaAc1ut4olDBW5mRmCc8wUFXnokFnZlswa7dMsnY1n9HR+3jVzykF9c7sCq2jQu/M+n54BFjeViUSvHW3kqz0FzhqtR2c1TyPK8+zIFK1/WxcFB8/1U2QzcSQBtC5vg97i3pFTyyuvB5AnvivX+MWT5rk6Z0bvjojVxZWLE38zXky9swycEdp69no5myJNLmTqP6jZWCiouGYiS0WB4=
  - secure: HhPM2n3VRTTL9V4P4yoT4CjjwA7Q/iXdyYy8sdkc/DgDKL5kyLmZn5NBou8VXuokTuE96ga26x5yoZEu30hkKpB8GIs6YyHLlq3ZoVL7DnTB9Ifp+hWcciWUWHMholCBc7lnFLJfI2s9gjxQumcv2yU9xwTg8uhhEpktw2TOMuXlxdON5u0iaFxueCSBTNEEhT/fJ0fsOW2cYtXumzqtdnx7Ovcw1kaul3Q74P8GseivkJ8VlSX/4kSFckLL6S8seuZxKVsb/VK0aXVq2I47Ok0jOugDpWbjz4feUMeDwm/0Z5D4CraIk49R8DWomxX7mgVqysEcQaPqauJJ8bBjsf8yPaqSKLSbLi+dCJIQHP+33NOBRvrS7MsCnZfprmDMmbBTCJYRgeP7rRl/Jy7LgmEAARpxit2CE6BgddVLqUaMq/WaW8frfl+BRq+mCTWyXQd2AaOSoLksqNIBtqvE73Bl9e8rPHgl+XkaTz7C4TWZKUJcP0bLzoGERyvXTyXjc0TTHDlINSAdtoRAtRmKr3CTYYDVTiLvVfswTXn9SnGZ3Dqnz5mX6MwGkpybsY7AE3xy2N0CO0cLIamnCCvjbZ99ZB7s3mDy5MhZFgyEWpFhgeIJCc6gljPTeHnCnNGDuGbIFdVY2xSX60i4J0xbBXHcPBNjRDIIl3QkbHBop7M=
