language: node_js

notifications:
  email: false

sudo: false

node_js:
- '6'

script:
- gulp build

after_success:
- gulp deploy --host $DEPLOY_HOST --user $DEPLOY_USER --password $DEPLOY_PASSWORD --path $DEPLOY_PATH

# Cache setup
cache:
  directories:
  - node_modules

# Variables
env:
  global:
  - secure: R+nSnDlFd1c50UQbJlGU0cmz//sjczPdTdBZzsLC7FRiN6PJe0sUmXehoe8w8t8X2EKjVDuGbwik4zoapxPk/D+Z3sNhuDQ1OzpYcfIhh7nAQ5DvE8ypyNN+Xv9D+mT8E8pW72xEx3scNi6HC4FtRlUBXDgB730sfGa6MRY6hkNWuZ+fMpebFejctrgI6Vh0dGjqIcWj6QwI5oIGEIT/bpxbwBctN9MRjOAv2pR0oVAtOwm0KcKkheHKq5nQMXGmwlsmG2M+5EdSEklzaaDR34+ca8LnjisfUAI4/BjyGFc5D9vePZH6qooMchINOkTMbX3u2Hy0YHA08nsEgeOyV/Yoy1ZG/Kgk5iI2aDsQkMniQamhLf//3P3XM5E0bi3/ZrqNGSt+ymRb++SMS/W6G+VbP7ssZtiFICK3wjWGPhk26hr+P1nRN6D34MaTgiBHRHWlGzLo76JGIT2zalBtJVbU6fKo30IXjwkUC591Q2D4UVFByUK8nzyCwtGYUhXtF6ar/kEl6DwIgXYEv1kbbrvgQ2Gg0HgcUPZmoRDrizahzRxUzJD1hmhDw9NoxLUOyzMvJ6UhbWUmEV+fUOHxyZ24+nUxEGuaiPx8xpIpW09HI3PoyEUuPZP2aZxpapYCtaSeWbc3ABni1rf86sEQGSTTYao46y9e8aY0OwFCj24=
  - secure: drLQuQaOehPjdHaVul5u3i+kzBKZzWrnwvlJZCXiFW7xSgf/ZhxfBzuDJJM/luh6CIgi/cWiIjJcKpxqfc6kBco0DDZNwJRqIumoohDp8jchdYJF+GIhTVK+3NRZwj7g5QesHmpEQ5j0/HkeLJdld56SZNafXvl6oV0mELaaupzCysLWS9JWRg5m3+A5d2tqwm1THHsrfI6ap2XTnLmUuB4zArZjf0SZXlDCHMsm3ZyKbs+hl1jp4QdSOyCrJChPoQxvoMeSUUsZS0xnuvHJDrWJFBMMDi0cZYO5O1Fhvwp4C9wC+0Vs8AvTtYlK7Qary0P5ofDjEZw1FEYyG0IuM8LDYJe8Ape03v4U204TH2nZfcu//Z8dwnMQGusVZcBP3p7KZslQ3dZ4PJR7e2HSBUx187X0FvpKRg4IQtLoIsD6Kk2hpwJJCKZ8f9v+jAj5cGhTyy5nxpcujLxuVyZtDqfRfHvL3PEsxDrgTgmtgNvC8hAqbTga+JsOVWyrLD8H3CZb1W8rcnjGS6EDfT0yxR9MPEumWUavEzvFjdzWiw1y3PMGYBdB8xBtETnPeZTl/6Vv9NQoUKEV2PnhDJyYMrWQE4nZHSrH4X5lVSjx7e0coRVjhCzB11LFMkWR5aNVQZBYA+VB81Bbvvnjfhf14uVyJjNP2suh1tOV+x5U+1s=
  - secure: IhG8a6jhvrw5gUAbedJ/frYXWQ6FOro9eqVlsrUdiuWzKU9NxgU2Zgcn/63B1UHtufchLSAUFOEpVa5A7k8zKxKjHy4uFDyk3OrlTO68dcIeDpyuJn2/f4V5y3nZTfW1YX9hbCGXEpQxa1wZtLqlz0mRk3RsMVClR7vrcsFxpNPRabODpHdT5RKL10QxDlnvmhMatox14PTI8pLbK6wQsVZL8TtIrXKqeRHt1Fajmevpd2+XdEXjtx0T/9FHHJ0URvOU4oLKaCgEipCRrxUW/Gb2OYChcMRahEPPylGJxw/HjE2KB/N8Tm+phUhm040HuuBU3Uw8/gdm5FSNxq0DMfjtGkuJC1lUD1MehIL+t0j60uDs3CGEMcGByoFhbp5N6OVINfEF4DMHfbOrmuaf9OXBWX1H8Zo7HQuSasTFhJaBvhuL1mg1Ac+c4VkmGjsVz0c7rlsUlLHm4YDWrXLutP8bff5g7xcUUGFYtZTzH5TEAWajFZd3pyumN8eUCZYDvxTIQx6OKPRJVyAbnCLqxbkfiCI3t6l+uuMcMFLV++N7vKqFZbdBDCzNU+XNVHcUDEaN5OXYQgo12LWgIXi/OncZ9rHVRj7v5satWsRL2ehlOoGAgw5p9l47Qwm4W+gS+KUskaqEk+BFmrmZqbb1vKiGMPV3Tfy+AUkfOui11Sk=
  - secure: uqCl64rcGCMHHvK7cVH44gYepuHhlN0lgDy97D6QEOMq5kX4MZg2uVRHQlnAnOXjMpD9SY8DRXF6zPyoqnYZ1UCvuhBSi0ZO2qR9UkLrtCeh8sAQikpRU2JAvCDAx1HeSTJPYNtEUYTKjnjEUyuEmw2SBGgcuOcogM22FraEtvYfFBOds+P3kgJce7MLuxBdZvxqoLyJxeL8ru2jnAlXW0FvVKMp8xJRFzhyBwYvmqvHsWswhwc7jWVGT7uxcGq07hJT6rk3+rMzMaFSSDHk+Ifb0bLfwrkY5Yb6zGkJni3kX5cgsTqxyKIZtpKtG18YM32DYBsXTg6JWm7n5b3G3NpXHkaRygiiUIOxKoYPqEl9yj6fxHNQEzptlZ+buKOMY9zxFJ0kNIfwBUp2hOJXQGN5Itb2aZMPn8ImPiRKiRy9ReisvbBSJFr9682wL9YBWLn/Kzh1RoQ5WlzFU7QmPGRm7dhqiAi+7+1Dbp2Q6GLcWiLjd2UkEA0tP2cP6m6msa3oh7VnUSNsO7n+S+YwonvTDV0I3Iz7/koPVmtsHkwywyD9BZ42LZ4zzhvySbHs9AgGMpXjWgP6AEIP4uk8F/Br0sMuf0ni82PaLlwjEBX1efcqbW2KsjTIk2EOc2Npj0mwp2uB88VMIrT2YJlqaSE3OWlK5wBc+Gs9byPFoSY=
