language: node_js

notifications:
  email: false

sudo: false

node_js:
- '6'

script:
- gulp build

after_success:
- gulp deploy --host $DEPLOY_HOST --user $DEPLOY_USER --password $DEPLOY_PASSWORD --path $DEPLOY_PATH

# Cache setup
cache:
  directories:
  - node_modules

# Variables
env:
  global:
  - secure: NYsY+0Rlx7Mf4vuKMDJtvt/mjaNzVNvhDdlYKAdmApZdA8oL5g+K16t8zVtOOOrX66iB+x72Lyx5KOyJtTV4sbGQ4Z9F1/p5DUKzIDoBYEw+iaqXLt3eTXU3s93c5fnq+ozpV4+2dYm0YwTC0fYKGS1JhtU8VaSmDpNBgbmipvoEzCPccPgMslxsv1M8Cn55AHJzBuaySuop3hLsaPGM+st9QtIB0/TZWvexZJecChBug/9Dlfce1w7yBS/cfC5OrpXaOqvjxiPkLdbNBnQ+mZOh9yjBF7ScdZniLEYsPiD9AtX/bijz1pHZhG/nqZfhG69xKSyDN0Uoyux5VGw7qaxXBJlMrX5NvbOWhpxP28oFsBPeJ8uX4jnbqOLRP8wdn7B4Hy/KzK2cEYX0QKz9DCYh1toK1Dk/8FiENrTCgIEwWWltrRHUBSg6xYY+dTx2Isi8WLk02C7u9uvgvPqMRpYEPoHpAth0fggkR85o7VlidZhmjPxY4q7KYM0q8q0XYKEn4RcnUDrFIF3rxKwmusSAgJz7dnwYaI9fY8Onlu4TgH+0cIMbGGAE2vAYmjgPW/PYFG43ylNktXKyc0cOJ0l86PznHySDHFaTwP+Jx6FXjYGa/mgDFVTy4uiP+cLyj5xqI6z/RfEP7lZZNEmOC85bWvr0/dKmH8CREJehgBc=
  - secure: MJFRtjkRuKbwCSY0ig0vsFaUaR40dIUr1/ODycYnTH1/KQ/Zsi2jBoDdqq9/2bP8t2QrxlUfV7xCzXV7HRxKcXQ80bUklBlY1aiEFaEbOBEBYz8e12SFa/JPc3SDXHhRyXooDkNzuhO4fAvXBte5SaQnCWjDODb0RTtIvrmQG7YK9DC038+VGddrxC9ldtYLVCsmXZg4u/8sZ3DvzVx7iVCFIDN6x2JK0tmEOkPXMBPikZBXoZhZppf9T7vpdcvBitOY2j8Q/Cb/tSXBI67QiVjoZGv/mwh59lFfsEKVs4T8EEJ9kGl/amgQBKJghzyqwpRPTDuisv4FizLMMZEQN3j8BqM/pLbe3yKcSTXQELAZva5q7aZYPXby2HLfjnuoDIUp2op8p5aeAdfg/P4QjLc74zH/SklTxvkBmtj4ULCIPlnQ6C57eNQdiGEdDrGb9+tTWYsy8lR2mjGQAseOTTvUsjfuzTVV0UYU2/GuJzWjoQf5hAadRiBn1biEH2GRe+7InS4aePKTO+tUkde3e1HVCpTW9aGC2Yq8y7qcVlN9o9SHHhnIORJ8j3ZXuKWkSg013JCJJ+XYBHZjiGIN3JOHJn6i9MeE54T+rho+xM7LOW8WXx3+j/MkHWBlgpG5YsBiDO1+3G1HBSMqp/IkVXKY5JuPByXXaTiSeppoXWc=
  - secure: oaJ+/PeT6faD6/vW4/0UgvWZEAaDg6TyIfAJyjpFXWrkR9pz5+V1n0ORosbayCy8qmWJPwOBZC+FVUZsKLmv2iuXyQRkzBWYHto8NWERzeVM/e4Qof0+JkBKjZiNP5r0E4WTAbY0xcYh/jiSVmNprVL4UjIer0oGC4VTJPCKQxdiW+swXGL2M+71elDSuafeTsC8PFfpfzdxvYD6lPj94tinSNQBge7uAZnpbgXcsH5w98gK6aG4OEL47pyfcw5LiFTCBVCGX7dHtzKwlI2u2LuZSCc07Atqo0u2RqqJRcFG5a0KU42F6ZEVTKXH80vcsKMqrm/DbVGlrMALhBIgW413ox1q3+o77KXfhQ2i5175u6gXundqcoqJ+p/KzN2vu1idVDy6s25hHiCqtVUK2+5Y7JB55Pr6WsLDTNF6IdZzXjl+ERjTIGTJe3/xhlO5Kvce3bXDss8pupDDnaeP1A3kXhxCm4kVffKMCmIMv3XPFJ6E0TlSeoljERcsHWMmbmxza2RJUNnGpl2ZU/M2RnT+QaeF4XUwASALCr1NeqZpvatN8ekF3cLIcB/0TBg+J6nis5bZ7YlVNNXhKjY82ebsVgrGFeITpojPvZQUSZ5/ifoWap6G/gYgw4WuYqB2/1idJeQNIo22kr8ak2mVA2xh1ACr4gT1RieCSTqdSJ0=
  - secure: vC+juowG2hkAT5f2dCvnm0wz7ppUtIU49e2uTUkFRLHrzsUWSZnWQsflrGiTlb7VgaLF4gF6VXNGvx/TrlK53CM1tV/4QwDMnSb9uLMFaOC+0m112kUSnR/AcjFGJyypWlNRe1FexXT0Ua9iqq0d+mq+jtpV6qFEesjlc/kRIxlmfvhe4CyCkk2IWVBOcLbv4IANO6zH4yi74BOSECUuxsvUAdQmKE2jJDMjR3/zimi9G5ZmmOq6BQiciJ/EQOQhasixZx6Ws2H+OXCzJGJZwDqYHWNr+fZ74ob4ZUKzkECf6aFjYksEhKxF4Cv7PAKbMewqEMralkjgKQFTEFT5ZtcW5M/BW3Zxb94fOpOkoeVizazu5qay05uiytWD8Y0ubPePBbMNpPnzEpvfeZCARy3ryniB0j5zRBv7C485pGK3xxm8qM8MK1i5gnwOa2oB0tGi2v3Ire6YnLoSIWP1VeFfrGaHs6Id6K1C5olRkn/1KYgeEI8ZmQCnzwBN5CyKZf+p4Ll7Q5HMwuLwQ+KEvDcOvlLFlB2zRSwN5lGUXq6ps3dw/Q2V6pNozgrcV/B/c7KsN8XxH/FrEmXhf9BWe4qCRNx1zf9AvWge/V60fmCpZUjrgs7OLrHkyGN7PkjW6t3a9MZQlYDgCNeduguKhx1WF++qa0cnMVBgOyNi3V8=
